name: model-training-pipeline

on: 
  push:
    paths:
      - '.github/workflows/deploy-model-training-pipeline.yml'
      - 'data-science/src/**'
      - 'mlops/azureml/train/**'
      - 'data/**'

jobs:
  get-config:
      uses: Azure/mlops-templates/.github/workflows/read-yaml.yml@main
      with:
        file_name: config-infra-prod.yml
  register-environment:
      needs: get-config
      uses: Azure/mlops-templates/.github/workflows/register-environment.yml@main
      with:
        resource_group: ${{ needs.get-config.outputs.resource_group }}
        workspace_name: ${{ needs.get-config.outputs.aml_workspace }}     
        environment_file:  mlops/azureml/train/train-env.yml
        conda_file: data-science/environment/train-conda.yml
      secrets:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          
  register-dataset:
    needs: get-config
    uses: Azure/mlops-templates/.github/workflows/register-dataset.yml@main
    with:
      resource_group: ${{ needs.get-config.outputs.resource_group }}
      workspace_name: ${{ needs.get-config.outputs.aml_workspace }}
      name: taxi-data
      data_file: mlops/azureml/train/data.yml
    secrets:
      creds: ${{secrets.AZURE_CREDENTIALS}}
      
  create-compute:
      needs: [get-config,register-environment,register-dataset]
      uses: Azure/mlops-templates/.github/workflows/create-compute.yml@main
      with:
        cluster_name: cpu-cluster
        size: Standard_D2_v2
        min_instances: 0
        max_instances: 4
        cluster_tier: dedicated
        resource_group: ${{ needs.get-config.outputs.resource_group }}
        workspace_name: ${{ needs.get-config.outputs.aml_workspace }}     
      secrets:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      
  run-pipeline:
      needs: [get-config,register-environment,create-compute,register-dataset]
      uses: Azure/mlops-templates/.github/workflows/run-pipeline.yml@main
      with:
        resource_group: ${{ needs.get-config.outputs.resource_group }}
        workspace_name: ${{ needs.get-config.outputs.aml_workspace }}     
        parameters-file:  mlops/azureml/train/pipeline.yml
        job-name: test
      secrets:
          creds: ${{secrets.AZURE_CREDENTIALS}}
  notify-deploy:
    needs: run-pipeline
    runs-on: ubuntu-latest
    steps:
    - name: Trigger deploy-batch-endpoint-pipeline # testing
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" \
          https://api.github.com/repos/cristobalcoddi/mlops-v2/dispatches \
          -d '{"event_type":"train_pipeline_completed"}'
